# Generated by Django 5.2.8 on 2026-01-06 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='duration_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
