# Generated by Django 5.2.8 on 2026-01-05 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_paymenttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='payment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.paymenttype'),
        ),
    ]
