# Generated by Django 5.2.8 on 2026-01-06 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_active',
            field=models.BooleanField(default=False, verbose_name='User Active'),
        ),
    ]
