# Generated by Django 5.2.8 on 2025-12-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demands', '0002_offer_is_active_offer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='details',
            field=models.JSONField(default=dict),
        ),
    ]
