# Generated by Django 5.2.8 on 2025-12-17 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_sector'),
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Onaylandı'), (0, 'Beklemede'), (2, 'Reddedildi')], default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_medias', to='company.company')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_medias', to='media.media')),
            ],
        ),
    ]
