# Generated by Django 5.2.8 on 2025-12-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_companymedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymedia',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
