# Generated by Django 5.2.8 on 2025-12-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_companymedia_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymedia',
            name='status',
            field=models.IntegerField(choices=[(0, 'Onaylandı'), (1, 'Beklemede'), (2, 'Reddedildi')], default=1),
        ),
    ]
