# Generated by Django 5.2.8 on 2026-01-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_company_created_at_company_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='social_media',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
