# Generated by Django 5.2.8 on 2026-01-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_company_social_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymedia',
            name='reject_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
